import re
import json
import time
import torch
import pipeline.models as models
from pipeline.utils import _llm, _parse_json

# ── Exact prompts from notebook Cell 5 ───────────────────────────────────────

_SYSTEM_MSG = """You are an advanced AI model trained to analyze and structure the medical conversations between a doctor and a patient."""

_USER_MESSAGE_TEMPLATE = """You are given a two party conversation transcript between a Doctor and a Patient that was generated by an ASR engine. The transcript does not contain speaker labels. Your task is to correctly assign speaker roles as Doctor or Patient based on the context.
Below is the guidelines for identyfying the speaker in for a given sentence:
1. Doctor's Role:
    * Asks diagnostic questions, gathers medical history, and provides medical insights.
    * Uses structured questioning (e.g., "What brought you in today?" "Have you experienced this before?
2. Patient's Role:
    * Describes symptoms, answers doctor's questions, and shares personal health information.
    * Responses are often personal experiences (e.g., "I have chest pain," "I smoke a pack a day.")


Output Instructions:
1. Provide the output in the following JSON format:
    [
        {
            "text": "<generated_text_with_speaker_labels>"
        }
    ]
2. Only add the Speaker Labels in the provided medical conversations which is given below. Don't add or remove original context.

Please strictly follow the above mentioned instructions and output should be strictly in above mentioned JSON format without any deviation. Don't include any instructions or steps in the output

Medical Conversations:
%s

Output:
"""

_SAMPLE_INPUT = """what brought you in today? Sure. I'm just having a lot of chest pain, and so I thought I should get it checked out. Okay. And before we start, could you remind me of your gender and age? Sure. I'm 39. I'm a male. Okay. And so when did this chest pain start?"""

_SAMPLE_OUTPUT = """[
    {
        "text": "Doctor: What brought you in today?\\nPatient: Sure. I'm just having a lot of chest pain, and so I thought I should get it checked out.\\nDoctor: Okay. And before we start, could you remind me of your gender and age?\\nPatient: Sure. I'm 39. I'm a male.\\nDoctor: Okay. And so when did this chest pain start?"
    }
]"""


class DiarizationAgent:
    """Adds Doctor:/Patient: speaker labels to raw ASR transcript."""

    def run(self, raw_transcript: str) -> str:
        print("[DiarizationAgent] Running speaker diarization...")
        t0 = time.time()
        torch.cuda.empty_cache()

        user_msg_example = _USER_MESSAGE_TEMPLATE % _SAMPLE_INPUT
        user_msg_actual  = _USER_MESSAGE_TEMPLATE % raw_transcript

        messages = [
            {"role": "system",    "content": _SYSTEM_MSG},
            {"role": "user",      "content": user_msg_example},
            {"role": "assistant", "content": _SAMPLE_OUTPUT},
            {"role": "user",      "content": user_msg_actual},
        ]

        outputs = models.pipeline_8b_instruct(
            messages,
            max_new_tokens=4096,
            eos_token_id=models.terminators,
            do_sample=True,
            temperature=0.2,
            top_p=0.9,
        )
        raw = outputs[0]['generated_text'][-1]['content']

        parsed_text = None
        try:
            parsed = json.loads(raw, strict=False)
            if isinstance(parsed, list) and parsed and isinstance(parsed[0], dict) and parsed[0].get("text"):
                parsed_text = parsed[0]["text"]
        except Exception:
            m = re.search(r'"text"\s*:\s*"((?:[^"\\]|\\.)*)"', raw, re.DOTALL)
            if m:
                try:
                    parsed_text = json.loads('"' + m.group(1) + '"')
                except Exception:
                    parsed_text = m.group(1).replace('\\n', '\n').replace('\\"', '"')

        torch.cuda.empty_cache()
        elapsed = round(time.time() - t0, 2)

        if parsed_text and parsed_text.strip():
            print(f"[DiarizationAgent] Done in {elapsed}s")
            print(f"[DiarizationAgent] Preview: {parsed_text[:200]}...")
            return parsed_text
        else:
            print(f"[DiarizationAgent] Could not parse LLM output as JSON. Falling back to raw transcript.")
            return raw_transcript
